name: 'Docker Action'
description: 'Build docker iamge and push to registry'
inputs:
  docker_file_name:
    description: 'File name of the docker file'
    required: false
    default: 'Dockerfile'
  app_root_path:
    description: 'Path to the docker file and application'
    required: false
    default: '.'
  image_name:
    description: 'Docker iamge name'
    required: true
    default: ''
  image_tag:
    description: 'Docker iamge tag'
    required: false
    default: 'latest'
  registry:
    description: 'Docker registry name'
    required: true
    default: 'https://index.docker.io/v1/'
  registry_username:
    description: 'Docker registry username'
    required: true
    default: ''
  registry_password:
    description: 'Docker registry username'
    required: true
    default: ''
outputs:
  time: # id of output
    description: 'Docker image pushed to registry'
runs:
  using: 'docker'
  image: 'Dockerfile'
