name: Docker push

on:
  workflow_dispatch:
    inputs:
      docker_file_name:
        description: 'docker_file_name'
        required: false

jobs:
  docker-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: docker-build-login-push
      uses: krmenon431/github-actions/docker-push@main
